pipeline {

    agent any
    tools {nodejs "nodejs"}
        stages {
                
            stage('Build11111') {
                
                steps {
                    sh 'docker pull node:lts-buster-slim'
                    sh 'docker run -d -p 3000:3000 --name my-docker node:lts-buster-slim'
                }
            }

        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}

